project:
  type: website
  output-dir: docs

website:
  title: "Dan Spitzer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - accom.qmd

format:
  html:
    theme:
      light: sandstone
      dark: superhero
    css: styles.css
    toc: true



